name: Code Quality on Pull Request
'on': pull_request

jobs:
  build_and_preview:
    if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install 

      # - name: Check linter conventions
      #  run: npm run lint

      - name: Run tests
        run: npm run test
